# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20180613_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumb',
            new_name='thump',
        ),
    ]
