# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20180613_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thump',
            field=models.ImageField(blank=True, default=b'default.jpg', upload_to=b''),
        ),
    ]
